# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'macos-latest' 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: false
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
# Archive the .ipa file for upload
- task: CopyFiles@2
  inputs:
    SourceFolder: 'ios/build/Release-iphoneos'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)/ipa'
  displayName: 'Copy IPA File'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)/ipa'
    ArtifactName: 'ipa'
    publishLocation: 'Container'
  displayName: 'Publish IPA Artifact'
